### ISSUE TITLE
It can't find libvala?

### ISSUE THREAD

**Issue by sprite-1** [philippejer/vala-language-server-alpha#11]
I'm trying to compile it but it's complaining that libvala is not installed. As you can see on the screenshot below, the same version is already installed

![image](https://user-images.githubusercontent.com/33685433/68260848-35178c80-0079-11ea-861d-71ddc19fd10c.png)

What could I be doing wrong here?

**Comment by gavr123456789** [comment]
@sprite-1 im from SuSe, but i think u need to install `-dev` version.

**Comment by philippejer** [comment]
Hi!

It seems you are using the "old" 0.40 version of the compiler which is standard in ubuntu 18.04, I have only tested the code with Vala 0.46.x.

So while you could install `libvala-0.40-dev`, I think it would not work well. For example, the `CodeVisitor` interface used to analyze the AST has changed in a recent version.

I try to use a recent stable version of Vala (currently 0.46.3 is my base version and seems stable enough).

Did you follow [these steps](https://github.com/philippejer/vala-language-server-alpha#how-to-compile-ubuntu-1804)? It's fairly quick to compile (5-10 minutes)...

I guess it would be possible to use a different version for the language server and for the regular compilation but I would not recommend it and I'm not sure how to do it (properly, anyway).

**Comment by gavr123456789** [comment]
I confirm, apparently on old compilers it doesnt build  
![image](https://user-images.githubusercontent.com/30507409/68341089-beba6f00-00f8-11ea-9bfd-1d7704fc33bb.png)

**Comment by sprite-1** [comment]
@philippejer sorry I thought installing `elementary-sdk` already gives me the latest `valac` so I skipped that part

**Comment by gavr123456789** [comment]
@sprite-1 oh, i didnt know that, ty for tip.

**Comment by philippejer** [comment]
No problem, thanks for the feedback :)

**Comment by sprite-1** [comment]
For anyone interested, I found out about a PPA that offers pre-compiled latest version of Vala

https://launchpad.net/~vala-team/+archive/ubuntu/next

If you don't want to go through the trouble of recompiling yourself.

**Comment by gavr123456789** [comment]
@sprite-1  It seems like you saw my question in telegram chat, ty again, but where the compile it self? There no valac, so i still need to compile it, but easier?

**Comment by sprite-1** [comment]
@gavr123456789 `valac` should be there too, I just checked

![image](https://user-images.githubusercontent.com/33685433/69472269-e2f99980-0de2-11ea-8af1-9366dd5febd7.png)

**Comment by gavr123456789** [comment]
@sprite-1  it's just ridiculous, but here's what I see in synaptic adding this repository:  
![image](https://user-images.githubusercontent.com/30507409/69480672-b3ff1a00-0e1a-11ea-9f88-516cf510bb90.png)  
![image](https://user-images.githubusercontent.com/30507409/69480678-be211880-0e1a-11ea-98b2-8a629c18427a.png)
Looks like i will just download deb package.

**Comment by gavr123456789** [comment]
Works with that .deb  
![image](https://user-images.githubusercontent.com/30507409/69480783-8b2b5480-0e1b-11ea-835e-d4c8b90fb8b3.png)
