### ISSUE TITLE
Add brace autocomplition(done) and code lens

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#14]
How about if function has no arguments -- complement it with empty brackets, and if it has do the same, but put the cursor in these brackets.

I assume that to put a semicolon on the end is'nt necessary as there are seq of functions(although this is a fairly rare case).  

Looks like Espinosa's GVLS is [doing ](https://youtu.be/fzK7kUcMP7s?t=18)something similar.

**Comment by philippejer** [comment]
Wow.. actually did not know about GVLS, it looks to be under very active development since 2-3 weeks, thanks for the heads up!

I should probably take a look at it and see if it is usable and if there are things that I can contribute (mostly VSCode/Windows specific stuff I guess), no need to to have thousands of language server :)

**Comment by philippejer** [comment]
Regarding your question, I have added some time ago a function for auto-insertion of brackets, which (I think) does exactly what you describe (but relies on a VSCode-specific command)...

It is controlled by a `vls.methodCompletionMode` setting. Here are my current settings for reference:

```jsonc
{  
  "vls.trace.server": "off",
  "vls.logLevel": "warn",
  "vls.methodCompletionMode": "nospace",
  "vls.referencesCodeLensEnabled": true,
  "editor.wordBasedSuggestions": false,
  // "editor.quickSuggestionsDelay": 300,
  "editor.suggestOnTriggerCharacters": true,
  // "editor.hover.delay": 500
}
```

**Comment by gavr123456789** [comment]
Thats reaaaly cool. Ye that's exactly what I wanted.   
![image](https://user-images.githubusercontent.com/30507409/69557612-f578fc00-0fb7-11ea-8894-c055e5f898ae.png)

**Comment by gavr123456789** [comment]
Also, how the code lens works?  
I created a function, and used it in another file, nothing like `references 1`, appeared.

**Comment by philippejer** [comment]
Thanks!

For code lens, you need to have built the latest master of the server and also install the 1.1.0 version of the extension...

Normally it should work then...

Note that I have pushed a big commit last Wednesday (20 november), there are a lot of improvements (see https://github.com/philippejer/vala-language-server-alpha/blob/master/CHANGELOG.md) but it might have broken something (hope not!).

**Comment by gavr123456789** [comment]
I have the latest versions of everything. Can you give an example in which CodeLens works exactly.

**Comment by philippejer** [comment]
Hi @gavr123456789,

Sorry about the delay... I have reverted to the standard Vala compiler from MinGW (0.46.3), rebuilt the language server (last commit https://github.com/philippejer/vala-language-server-alpha/commit/ecc7cbfae40ad531a7d0267ceac9697fce49ef2c) and I have forked your project to check: https://gitlab.com/philippejer/system-models/tree/test-vls

It seems to work fine (at a glance), I have code lens references (note that it only works for method and properties, like in C#) and automatic parenthesis insertion.

![image](https://user-images.githubusercontent.com/10595772/69727238-69cfae80-1122-11ea-80ee-c74668110f1a.png)

Maybe a thing to note is that the `.vscode/settings.json` file must be at the root of your workspace (so in this instance, you need to open the `system-models/2` folder, not the `system-models` folder)...

**Comment by gavr123456789** [comment]
I once again installed the language server all, and downloaded your fork of my lab system modeling. And nothing. Also vala version was updated to 0.46.4. Maybe that's the case, though I highly doubt it. There is a possibility that I did something inattentively, when I get home I'll try again.
![image](https://user-images.githubusercontent.com/30507409/69796964-fc825300-11df-11ea-9ae0-9a23c3aa36bd.png)

**Comment by philippejer** [comment]
Ah it's frustrating, it seems you did everything right...

Maybe you could enable the protocol-level logs (Vls -> Trace: Server) to see the client actually sends the codeLens request?

I get something like this in my traces (Output -> Vala Language Server):

```
[Trace - 3:52:13 PM] Sending request 'textDocument/codeLens - (55)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/system-models/2/calc.vala"
    }
}


[Trace - 3:52:13 PM] Received response 'textDocument/codeLens - (55)' in 2ms.
Result: [
    {
        "range": {
            "start": {
                "line": 5,
                "character": 1
            },
            "end": {
                "line": 5,
                "character": 14
            }
        },
        "data": {
            "textDocument": {
                "uri": "file:///d%3A/system-models/2/calc.vala"
            }
        }
    },
```

**Comment by gavr123456789** [comment]
![image](https://user-images.githubusercontent.com/30507409/71298894-5b7c5780-239b-11ea-9675-c31b661b7fa5.png)  
I changed the distribution to Arch, and everything works here, I also checked for Elementary. I assume that with OpenSUSE was something wrong, and with a clean installation CodeLens will work. Im closing it.
