### ISSUE TITLE
Autocomplite constructors with <type>

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#19]
> I will (normally) have more time during the holidays.

^^  
Autocompletion does not work for regular and named constructors.  
I mean autocomplete parentheses and prompt arguments if the constructor has parameters. Or hint other named constructors.  
  
Minimal Example:  
```vala
struct Op {
        public Op(OpT _op, int _v) { op = _op; v = _v; loop = null; }
        public Op.with_array(OpT _op, Op[] _l) { op = _op; loop = _l; v = 0; }
    }

var op = new Op
//Expectation - after pressing enter, the Op prompt will display
// `Op (cursor here)` or when setting a point after
// the op show prompt `Op.with_array(cursor here)`
```

**Comment by philippejer** [comment]
Ah yes, I've left constructor completion as a second-rate priority as it is a bit tricky to handle with the "quick and dirty" approach to completion, but I've wanted to work on it for some time, these are good example to start with :)

**Comment by gavr123456789** [comment]
Ye, i understand, think will really hard to implement autocomplition for things like   
`var a = new ArrayList<string>.from_array()`

**Comment by gavr123456789** [comment]
All works good !  
![image](https://user-images.githubusercontent.com/30507409/71557776-f3dda080-2a5b-11ea-8056-122f8dc6d74a.png)

**Comment by gavr123456789** [comment]
oh, even there, nice  
![image](https://user-images.githubusercontent.com/30507409/71557906-f17c4600-2a5d-11ea-89bc-f19a5236c754.png)

**Comment by philippejer** [comment]
Thanks for the feedback!

Note that proper completion of generic type parameters are a bit problematic, the protocol is very basic (and also the fact that the `<` character is both a delimiter and an operator does not help ;) )

**Comment by gavr123456789** [comment]
@philippejer PS, what does that mean "- Add "fake" symbols for array types"  ?
