### ISSUE TITLE
Autocomplite after \n in call sequences

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#20]
Works:  
![image](https://user-images.githubusercontent.com/30507409/71451293-7aa42c00-2783-11ea-959d-b236634ade65.png)
  
Not works xd:  
![image](https://user-images.githubusercontent.com/30507409/71451296-9ad3eb00-2783-11ea-9530-17c85a6dd659.png)
  
So using libraries like [gpseq](https://gitlab.com/kosmospredanie/gpseq)(one of the coolest libraries written in Vala for Vala, go try it if you haven't already) will be very problematic. I don't think this is a very difficult problem, something like "ignoring the previous `\n` when autocompletion" should fix it.

**Comment by philippejer** [comment]
Hi @gavr123456789,

Finally back! Thanks for the pointer to this library, it looks incredibly well-written, lots to learn from it.

I've just pushed a commit which should solve this issue.

Just to warn you, the commit just before that has many modifications, I've been careful but please tell me if I've broken something, I should have some time to fix it.

(these are mostly non-functional modifications (also some bug fixes), I've been trying to improve the non-null mode of the compiler to avoid having to do a million casts when the compiler can statically prove that a variable is not null in a given branch)

**Comment by gavr123456789** [comment]
nice, will check when I wake up xd

**Comment by gavr123456789** [comment]
Looks like all works fine. I haven't found any new bugs yet. ^^
![image](https://user-images.githubusercontent.com/30507409/71568107-971ecc00-2ad5-11ea-83c1-27c8e1996c17.png)
  
But I noticed that autocomplete doesn't work in lambdas
![image](https://user-images.githubusercontent.com/30507409/71568155-fb419000-2ad5-11ea-8326-51875593f5ac.png)
  
at the same time, it works in such strange places as for, that nice.
![image](https://user-images.githubusercontent.com/30507409/71568171-21ffc680-2ad6-11ea-8e22-79e22765d5e2.png)

**Comment by gavr123456789** [comment]
Also if u didnt know that cool hack.  
```vala
[Print]
void prin(string s){
    print(s + "\n");
}
prin(any variable that have to_string, " ", a, " ", b, ...)
```  
This code attribute causes vala to automatically apply `to_string` to everything that takes the function it marked, so you can create a very beautiful way of output without intropolation of strings. Just like an overloaded << operator in C++.
