### ISSUE TITLE
Json-WARNING Failed to deserialize ...

### ISSUE THREAD

**Issue by darkoverlordofdata** [philippejer/vala-language-server-alpha#25]
first of all, thank you - this worked great on debian-buster. It found issues that I had missed, like not wrapping my io code with try/catch.

But I've switched to FreeBSD, 
vala version = 0.47.2
meson version = 0.52.1
OS = FreeBSD 12.1-RELEASE-p1 r355402 NOMADBSD 
vscode (Code OSS) version = 1.41.0.

Now I get errors initializing. I realize this project is in a hiatus, but maybe you can point me to where in the code this is error comes from, and I can look at it

vala-language-server.json = 
```
{
  "sources": [
    "src"
  ],
  "parameters": "valac \"-C\" \"--vapidir=./vapi \"  \"--enable-gobject-tracing\" \"--define\" \"LIBVALA_EXP\" \"--pkg=posix\" \"--pkg\" \"gio-windows-2.0\" \"--pkg\" \"libvala-0.47.2\" \"--pkg\" \"jsonrpc-glib-1.0\" \"--pkg\" \"gio-2.0\" \"--pkg\" \"gee-0.8\" \"--pkg\" \"gobject-2.0\" \"--target-glib\" \"2.56\" \"--pkg\" \"glib-2.0\""
}
```
error:
```
** Message: 11:20:09.573: Main.vala:21: Server running in Unix (API version: 0.48, BUILD version: 0.47.2...

(process:36260): Json-WARNING **: 11:20:09.584: Failed to deserialize "rootUri" property of type "(null)" for an object of type "VlsInitializeParams"

(process:36260): Json-WARNING **: 11:20:09.584: Failed to deserialize "initializationOptions" property of type "(null)" for an object of type "VlsInitializeParams"
[Info  - 11:20:09 AM] Connection to server got closed. Server will restart.
** Message: 11:20:09.667: Main.vala:21: Server running in Unix (API version: 0.48, BUILD version: 0.47.2...

... repeats several times, then ...

[Error - 11:20:10 AM] Connection to server got closed. Server will not be restarted.

```

**Comment by philippejer** [comment]
Thanks for the report!

I know this error, you need to compile and install the latest master of json-glib (I have provided some steps for Ubuntu [here]( https://github.com/philippejer/vala-language-server-alpha#compile-and-install-json-glib)).

I have recently merged a bugfix into this library and removed the corresponding workaround in the language server.

To be consistent, I would also recompile the latest version of jsonrpc-glib from source too.

I'll see if I can update the Meson build file to detect that the library is not recent enough (and probably make it more obvious in the README).

**Comment by darkoverlordofdata** [comment]
Thank you, that fixed it. I thought my installed version of json-glib was new enough, but it wasn't.
