### ISSUE TITLE
Object members autocomplete doesn't work

### ISSUE THREAD

**Issue by ChronosXYZ** [philippejer/vala-language-server-alpha#33]
When I try to get completion list of some symbol, after typing `.`, server doesn't respond with list of member methods/properties available to call/get.

**Comment by gavr123456789** [comment]
What vala version u have?   
See https://github.com/philippejer/vala-language-server-alpha/issues/31

**Comment by ChronosXYZ** [comment]
@gavr123456789 I have Vala 0.48 ._.
But issue that you mentioned doesn't related to my issue. In logs I don't see any similar messages.  
Log messages which possibly related to my issue:
```
vls: main.vala:716: Request (78): context updated
vls: main.vala:1742: [textDocument/completion] FindSymbol @ 25:11
vls: main.vala:1749: [textDocument/completion] no results found for member access
vls: main.vala:182: Got call! textDocument/documentSymbol
```

(btw I have some questions related to this language server in general, I'm Russian too, so where we can chat?)

**Comment by gavr123456789** [comment]
@gavr123456789 I have telegram [Vala channel](https://t.me/codefaq)

**Comment by ChronosXYZ** [comment]
Oh sorry, I'm closing this issue because it's related to https://github.com/benwaffle/vala-language-server
