### ISSUE TITLE
[Info] Works on Arch!

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#5]
I installed arch, and so far it works great, just want to share it.  
![image](https://user-images.githubusercontent.com/30507409/67129968-b8775800-f208-11e9-8244-8aca4e03019f.png)  
  
![image](https://user-images.githubusercontent.com/30507409/67129991-c5944700-f208-11e9-96cf-d3e5b7b42f61.png)

![image](https://user-images.githubusercontent.com/30507409/67130343-afd35180-f209-11e9-962d-740f4afdbfcd.png)

**Comment by philippejer** [comment]
That's great, thanks for testing!

I've just updated the code (a few bugfixes/improvements and some code reorganization).

I've also committed small but helpful one-liner hack on the parser [in this branch](https://gitlab.gnome.org/philippejer/vala/tree/0.46.3-exp), it's really nice to be able to navigate the code when a semicolon is missing or something trivial like that.
