### ISSUE TITLE
Release:  Failed to execute helper program (Invalid argument) Windows

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#7]
Windows
```
** (process:9220): WARNING **: 21:33:24.999: Server.vala:147: Uncaught error: Failed to execute helper program (Invalid argument))

** (process:9220): WARNING **: 21:33:24.999: Server.vala:148: Consider using the 'Restart server' command (VSCode) to restart if this is a transient error
[Error - 21:33:25] Server initialization failed.
  Message: Failed to execute helper program (Invalid argument)
  Code: -32603 
Server running in Windows (debug level: warn, API version: 0.46, BUILD version: 0.46.0.1-65546-exp)...
```

**Comment by gavr123456789** [comment]
Is this about that`gspawn-win64-helper-console.exe` file?

**Comment by philippejer** [comment]
Yes absolutely, it is required by the implementation of `g_spawn_xxx ()` in Win32 to get the program output etc. (see the header of https://github.com/GNOME/glib/blob/master/glib/gspawn-win32.c).

Normally, I have included the correct one (gspawn-win64-helper-console.exe) in the ZIP file.

**Comment by gavr123456789** [comment]
Ye i see, so what i need to do with it? Looks like vls cant find it, and there no option to setup its path.

**Comment by philippejer** [comment]
Mmm.. that's strange, I have just checked that it works on my side even without MinGW on the PATH, and if I remove `gspawn-win64-helper-console.exe` I have the exact same error ("Failed to execute helper program (Invalid argument)").

I guess it explains why you could not launch Meson previously...

In the meantime, you can just dump a `vala-language-server.json` file at the root of your project which looks like this (for example for your test project):

```json
{
  "sources": [
    "v.vala"
  ],
  "parameters": "--pkg gobject-2.0 --pkg glib-2.0"
}
```

It's a bit tedious to have to maintain two files, but at least it's explicit and it removes that dependency to Meson which has given me issues from the start...

Note that in general `parameters` should match what is generated by Meson inside `compile_commands.json` or `build.ninja` (but mostly only the `--pkg` and `--define` flags are really important).

**Comment by gavr123456789** [comment]
Will try it tomorrow. Havent time now (its 02:42 heh)

**Comment by gavr123456789** [comment]
Closed with https://github.com/philippejer/vala-language-server-alpha/issues/8

**Comment by gavr123456789** [comment]
Closed with https://github.com/philippejer/vala-language-server-alpha/issues/8

**Comment by philippejer** [comment]
See my comment here https://github.com/philippejer/vala-language-server-alpha/issues/3#issuecomment-552890895, it seems that this issue is caused by the "legacy" mode of the console, and it explains why the binary version complained about not finding `gspawn-win64-helper.exe`.
