### ISSUE TITLE
Will check release on 8 pc

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#8]
I something like the moderator ( teacher in sections for schoolchildren on programming) of eight computers. Tomorrow I will try to install Language Server. This will make it clear on whose side the problem is. (Is there something special done on your computer, or is there something wrong with mine)

**Comment by philippejer** [comment]
Thanks @gavr123456789 that will be useful.

I'm on a basic Windows 10 x64 desktop PC (tested with two similar PCs). Also tested under Windows WSL (Ubuntu 18.04) and it worked fine (probably better actually).

Also check out the latest binaries (1.0.2), you can now use directories in `vala-language-server.json` [like this](https://github.com/philippejer/vala-language-server-alpha/blob/72ef038b4873a30d0720dd87839710aeadd5d5ad/vala-language-server-test.json), it is really easy.

**Comment by gavr123456789** [comment]
Can u say more about that vala-language-server.json.  Its looks like vls source compilation command. How do I use this? (I have a very bad understanding of the structure of VS Code extensions)    

I get the same error on another computer. What I do: Unpack the zip, install the extension, specify the path to the exe in the settings.
```
** (process:6172): WARNING **: 13:57:39.942: Server.vala:147: Uncaught error: Failed to execute helper program (Invalid argument))

** (process:6172): WARNING **: 13:57:39.942: Server.vala:148: Consider using the 'Restart server' command (VSCode) to restart if this is a transient error
[Error - 13:57:39] Server initialization failed.
  Message: Failed to execute helper program (Invalid argument)
  Code: -32603 
Server running in Windows (debug level: warn, API version: 0.46, BUILD version: 0.46.0.1-65546-exp)...
```

```
 "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "vls.path.server": "C:\\Users\\tutor\\vala-language-server\\bin\\vala-language-server"
```

**Comment by gavr123456789** [comment]
Oh waiiiit, when i tryed to run `gspawn-win64-helper-console` standalone i got that! :  
![image](https://user-images.githubusercontent.com/30507409/67567057-e0e3e280-f731-11e9-9346-0fd683719f4d.png)
>"Windows has protected your computer "   

I chose "execute anyway", expectedly nothing has changed, as far as I understand this exe is passed the wrong arguments, and in that json just they are.

**Comment by gavr123456789** [comment]
Oh, I read your notes on commits and understood everything, all works now, but emphasizes everything related to GTK, I suppose you need to put Vapi next to it and specify it in src. In some of the VSLs that worked on Atom (very bad) there was the same problem, but on Linux. I suggest as a solution to add the path to msys64\mingw64 in the extension settings so that vls knows where to look for Vapi. (Of course, this option will only be used on windows)
P.S. Yaaay  
![image](https://user-images.githubusercontent.com/30507409/67568521-1938f000-f735-11e9-99d3-1d13c1e7d326.png)

**Comment by gavr123456789** [comment]
Works on all 8 machines
